### ISSUE TITLE
Crashes 1.16.2

### ISSUE THREAD

**Issue by andybno1** [Olafski/FastLeafDecay#39]
Cannot start 1.16.2 get the following in crash log

[31Aug2020 08:48:30.314] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing License, please supply a license. (FastLeafDecay-v23.jar)

**Comment by blizzard4591** [comment]
@Olafski  See https://github.com/MinecraftForge/MinecraftForge/issues/7184 for infos on how to fix this.
A good example is also here: https://github.com/StrikerRockers-Mods/VanillaTweaks/commit/2e1c42762d7529062d0146a1fb0a2102db3149af

@andybno1 I used the v23 jar and only changed the missing license, seems to work fine with 1.16.2 (but no guarantees): 
[FastLeafDecay-v23_with-license.zip](https://github.com/Olafski/FastLeafDecay/files/5151362/FastLeafDecay-v23_with-license.zip)

**Comment by Olafski** [comment]
@andybno1 Thanks for reporting this. I've uploaded a version 24 to Curseforge which should fix this.

@blizzard4591 Thanks for the tip! I couldn't really find any documentation on this field so I took the example you made. Took me a while before I figured out it had to go at the top of the file, not in the [mods] section. 😊

**Comment by blizzard4591** [comment]
Ah, I should have said that, I made the very same mistake and wondered why it did not work. Sorry about that!

**Comment by Olafski** [comment]
No problem! I lost way more time figuring out why the Twitch launcher wouldn't start my custom profiles. Couldn't figure it out and went with a manual install of Forge :S

It bugs me a little that they (both Mojang and Forge) keep making such changes in minor version bumps...

**Comment by Olafski** [comment]
No worries about last comments, I don't mind interaction ;)

To be honest, I couldn't figure out how to do all the different minecraft versions properly in a repository. I don't do a lot of Java so for every new version that comes out, I have to figure out how to make a workspace again. 

Since the code is quite different each time, branches didn't seem to make sense to me. I currently have a `MC Mod Dev` folder on my hard drive with just a different folder with MDK for each version of Minecraft, which is a mess. Since I very rarely even go back to older versions it didn't really make a whole lot of sense to me to even use source control.
