### ISSUE TITLE
FastLeafDecay hard crash with The Abyss Chapter II 

### ISSUE THREAD

**Issue by iobiarg** [Olafski/FastLeafDecay#46]
Getting a crash each time i break any vegetable (like grass)...
[latest.log](https://github.com/Olafski/FastLeafDecay/files/5986363/latest.log)

Already happened 3 times, already reported to The Abyss Devs.

**Comment by Y3Z0N** [comment]
Note from the Dev (AbyssCp2)

"Fast Leaf Decay tries to find a persistent value in the Blueberry Leaves block but it doesn't have one. Game crashes when loading dimension."

your mod "fastleafdecay" checks for values that don't even exists. abyss don't use the leaf decay feature. you should probably add a way to check if the existing block uses leaf decay inside the Minecraft:leaves tag. there are some other mods who don't use leave decay and there's the same situation (checked 5 mins ago) result = gatecrash caused by fastleafdecay.

**Comment by Olafski** [comment]
Which version of FastLeafDecay are you using? I don't see the mod name mentioned anywhere in your log. 

My mod (at least recent versions) checks if a block inherits from `LeavesBlock`. As far as I know, it does nothing with persistent values or anything like that. If other mods create blocks that inherit from leaves but somehow aren't leaves, I'm not sure what to do with that.

**Comment by TelepathicGrunt** [comment]
Actually the best practice would be instead of doing .get( to get a property of a block right away, it’s always wise to do a .hasProperty( check beforehand. There’s always gonna be edge case blocks you will come across so always check that it has the property first before obtaining it

**Comment by TelepathicGrunt** [comment]
@iobiarg @Y3Z0N you two got the wrong mod lmao
It's Rapid Leaf Decay that is crashing. Not Fast Leaf Decay lol
@iobiarg You can close these issue reports. I'll go poke the actual mod in question

**Comment by Y3Z0N** [comment]
from my side out #closed
Because of reporting to the wrong mod. Im sorry sadly i thought this was the github for RapidLeafDecay. names confused me.

**Comment by Olafski** [comment]
Well, that clears up a lot of confusion! Thanks for the followup people. :)
