### ISSUE TITLE
Support Wisteria leaves from Environmental

### ISSUE THREAD

**Issue by chimericdream** [Olafski/FastLeafDecay#48]
I am cross-posting this issue both here and [in the Environmental repository](https://github.com/team-abnormals/environmental/issues/189), since I'm not sure in which place the change needs to be made.

The Wisteria leaves from the Environmental mod don't decay like others. Looking at their code, it appears that the `WisteriaLeavesBlock` inherits from `Block` instead of `LeavesBlock`. Would it be possible to add support here for them? On the CurseForge page you mention that "Other mods that don't inherit the Minecraft leaves functionality (such as Thaumcraft) will not work unless I specifically support them.", which implies that the change _could_ be made here.

It looks like the actual code in this repo hasn't been updated, but I know the mod is still active. I'd be happy to submit a PR if you have the code in another location.

**Comment by Olafski** [comment]
Hey chimericdream, thanks for raising this issue.

While it is true that I mentioned that blocks need to inherit from `LeavesBlock`, unfortunately that still does not mean I can just add another base class to support other leaves. In theory I could, but that would be limited to blocks that are included in Minecraft by default. Otherwise my mod would have to depend on the mod that the block is defined in, which I'm sure you'll understand I would prefer not to do.

Probably your best bet would be to ask the developers of the other mod why their leaves blocks don't inherit from `LeavesBlock`. I'm guessing that is because they wanted to specify different behavior for them, which would make it difficult to fix compatibility between the mods. But it's still worth a shot. ;)

**Comment by Olafski** [comment]
A bit of a late reply, but I just released a new version of FastLeafDecay which also checks the `leaves` BlockTag. Tested with Environmental, and their trees are now supported! :-)
