### ISSUE TITLE
Reduced Drop Rate

### ISSUE THREAD

**Issue by y8ycgl** [Olafski/FastLeafDecay#7]
I have a server set up for some of my friends, and I use Fast Leaf Decay on the server. Many users are reporting a decreased amount of saplings from trees. Something appears to be changing the drop rate of sapplings somehow.

**Comment by Olafski** [comment]
Hey y8ycgl,

I've had this reported on my Curse page as well, about a year ago. In response to that I have done extensive tests, counting saplings with and without the mod, and concluded that there was no difference between the two. The way the mod is setup, it just speeds up decay; drop rates are handled by Minecraft.

Let me know if you find otherwise, but please include some research so I know what to look for.

Olafski

**Comment by y8ycgl** [comment]
Alright. Thank you. There was a discussion where some research was done in my group and they actually may be crazy. Sounds like you are correct.
